# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_backend import file_service_pb2 as grpc__backend_dot_file__service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_backend/file_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertToPng = channel.unary_unary(
                '/FileService/ConvertToPng',
                request_serializer=grpc__backend_dot_file__service__pb2.FileRequest.SerializeToString,
                response_deserializer=grpc__backend_dot_file__service__pb2.FileResponse.FromString,
                _registered_method=True)
        self.BatchConvertToPng = channel.unary_unary(
                '/FileService/BatchConvertToPng',
                request_serializer=grpc__backend_dot_file__service__pb2.BatchFileRequest.SerializeToString,
                response_deserializer=grpc__backend_dot_file__service__pb2.BatchFileResponse.FromString,
                _registered_method=True)
        self.UploadDicom = channel.unary_unary(
                '/FileService/UploadDicom',
                request_serializer=grpc__backend_dot_file__service__pb2.UploadRequest.SerializeToString,
                response_deserializer=grpc__backend_dot_file__service__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.QueryTags = channel.unary_unary(
                '/FileService/QueryTags',
                request_serializer=grpc__backend_dot_file__service__pb2.TagQueryRequest.SerializeToString,
                response_deserializer=grpc__backend_dot_file__service__pb2.TagQueryResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertToPng(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchConvertToPng(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDicom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertToPng': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertToPng,
                    request_deserializer=grpc__backend_dot_file__service__pb2.FileRequest.FromString,
                    response_serializer=grpc__backend_dot_file__service__pb2.FileResponse.SerializeToString,
            ),
            'BatchConvertToPng': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchConvertToPng,
                    request_deserializer=grpc__backend_dot_file__service__pb2.BatchFileRequest.FromString,
                    response_serializer=grpc__backend_dot_file__service__pb2.BatchFileResponse.SerializeToString,
            ),
            'UploadDicom': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDicom,
                    request_deserializer=grpc__backend_dot_file__service__pb2.UploadRequest.FromString,
                    response_serializer=grpc__backend_dot_file__service__pb2.UploadResponse.SerializeToString,
            ),
            'QueryTags': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTags,
                    request_deserializer=grpc__backend_dot_file__service__pb2.TagQueryRequest.FromString,
                    response_serializer=grpc__backend_dot_file__service__pb2.TagQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertToPng(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileService/ConvertToPng',
            grpc__backend_dot_file__service__pb2.FileRequest.SerializeToString,
            grpc__backend_dot_file__service__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchConvertToPng(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileService/BatchConvertToPng',
            grpc__backend_dot_file__service__pb2.BatchFileRequest.SerializeToString,
            grpc__backend_dot_file__service__pb2.BatchFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDicom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileService/UploadDicom',
            grpc__backend_dot_file__service__pb2.UploadRequest.SerializeToString,
            grpc__backend_dot_file__service__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileService/QueryTags',
            grpc__backend_dot_file__service__pb2.TagQueryRequest.SerializeToString,
            grpc__backend_dot_file__service__pb2.TagQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
